### ISSUE TITLE
 java.util.ConcurrentModificationException while searching contact

### ISSUE THREAD

**Issue by vovander** [quiin/UnifiedContactPicker#5]
`E/AndroidRuntime: FATAL EXCEPTION: 
                                                                    java.util.ConcurrentModificationException
                                                                        at java.util.ArrayList$Itr.next(ArrayList.java:831)
                                                                        at mx.com.quiin.contactpicker.adapters.AutoCompleteAdapter$ContactFilter.publishResults(AutoCompleteAdapter.java:112)
                                                                        at android.widget.Filter$ResultsHandler.handleMessage(Filter.java:282)
                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                        at android.app.ActivityThread.main(ActivityThread.java:6121)
                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)`

**Comment by hessekwei** [comment]
im getting the same error.
